### ISSUE TITLE
Possible missing polyswarm-client dependency

### ISSUE THREAD

**Issue by CalebFenton** [polyswarm/participant-template#54]
`polyswarm-client` is [listed as a dependency in `setup.py`](https://github.com/polyswarm/participant-template/blob/c879521d72420af97dfa769553d61d11db551f04/%7B%7B%20cookiecutter.project_slug%20%7D%7D/setup.py#L13
), but not in `requirements.txt`. Is there a reason for this?

I also don't think `install_requires` are considered when installing with `python setup.py install` as was recently introduced in the [Dockerfile](https://github.com/polyswarm/participant-template/blob/master/%7B%7B%20cookiecutter.project_slug%20%7D%7D/docker/Dockerfile#L43). All your dependencies will be installed with `pip install .` but I figure there's a reason you switched away from that.

**Comment by mrtizmoatwork** [comment]
Hey @CalebFenton , you are correct, `polyswarm-client` should also be listed in `requirements.txt`. 

However, `python setup.py install` installs the base package and any dependencies defined in `install_requires` section of `setup.py`. See `setup.py` docs regarding use of `install_requires` : https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies. 

Related `pip install --no-cache-dir -r requirements.txt` only installs packages listed in the `requirements.txt` file, and does not install the package defined by `setup.py`.

The reason we do both is to enable better docker layer caching. If you are doing development such that the `requirements.txt` content does not change often, but the code of your project is obviously changing often, then you can rebuild the docker image and take advantage of the existing layer that already includes all of your `requirements.txt` dependencies.

**Comment by myhndl** [comment]
Hey @CalebFenton thanks for bringing this up.

Yeah @mrtizmoatwork is exactly right - the `pip install` earlier in Dockerfile and `python setup.y` later in the Dockerfile are precisely amenability to Docker caching.

However, I believe the lack of `polyswarm-client` in requirements.txt was actually intentional. Generally, we don't want to support development outside of Docker containers - and by not including `polyswarm-client` in requirements.txt, but basing the Dockerfile on `polyswarm/polyswarm-client`, we effectively force people to build a Docker image and do development in there.

Internally, we typically develop with either PyCharm or VSCode - both of which support interactive, in-Docker-container debugging, breakpointing, etc:
* https://code.visualstudio.com/docs/remote/containers
* https://www.jetbrains.com/help/pycharm/using-docker-as-a-remote-interpreter.html

That said, I don't have a super strong opinion about effectively un-breaking local installation outside of a Docker container - is there a use case I'm missing? Is this about debugging locally or something else?

**Comment by CalebFenton** [comment]
My problem is that I didn't catch the earlier `pip install`. This is exactly the idiom I use to speed up docker builds, and that makes total sense, so all good there.

@myhndl Thanks for explaining your reasoning for leaving it out. I use intellij and I'm not sure if it's smart enough to parse setup.py for dependencies. If I add a requirement to requirements.txt, the IDE immediately notifies me that it's not installed. If it's only present in setup.py, there's no notification or prompt to install it. I would imagine PyCharm works similarly since it's also made by jetbrains.

As for being forced to use docker, one of the first things I did was get pytest working locally so I didn't have to wait for docker to rebuild containers and for tox to download, compile, and otherwise install a bunch of dependencies every time I wanted to make some small change and run unit tests. Using docker for integration tests seems like a really good idea, and I'd run my unit tests in docker when I was sure they ran with pytest. If you really want to force devs to use docker for unit tests, there might be a way to run a tox command to build the environment during the container build process, but I couldn't see one.

**Comment by myhndl** [comment]
On mobile, but real quick: tox is not using anymore. It's not in template. Precisely for the reason of reinstalling existing deps.

Are you adding to your engine or are you based on a template that included it?

I'd recommend just using pytest.

**Comment by CalebFenton** [comment]
I ran cookiecutter a few weeks ago and haven't "rebased" since then. If
it's fixed now, that's cool.
