### ISSUE TITLE
Possible documentation mix up and odd assumption in test_scan_random_mal_not

### ISSUE THREAD

**Issue by CalebFenton** [polyswarm/participant-template#62]
The docs for ScanResult object within file_scan don't match what ScanResult says. According to docs within file_scan the `bit` field is:
> a boolean representing a malicious or benign determination

And `verdict` is defined as:
> another boolean representing whether the engine wishes to assert on the artifact

This is oddly worded and opposite of what ScanResult says. Maybe you shouldn't include ScanResult documentation in file_scan. A modern IDE can navigate to ScanResult documentation in a click. It also doesn't document confidence.

Somewhat related: the default unit test for test_scan_random_mal_not asserts that `result.bit` is always true. This assumes a scanner will always have an assertion about the benign file, even if the benign file isn't a scannable type. You can for _sure_ check the bit field is true if the verdict is also true or should be true.

**Comment by myhndl** [comment]
Thanks for the report, you're absolutely correct: `bit` and `verdict` were somehow transposed in the source code comments. I agree, they probably shouldn't be in the comments at all anyway. I'll open a PR to remove.

Regarding the `bit` assertion check ...

If we assume engines operate in a conviction model (presumption of innocence), then a `True` value for `verdict` should always be accompanied by a `True` `bit`, because a `True` verdict is to not accept the default response (benign). 

If instead, an engine operates on a exoneration model (presumption of guilt), the opposite is true - a `True` `verdict` may or may not be accompanied by a `True` `bit`, but a `False` `verdict` certainly would.

I think it's far more likely that engines take a conviction model, but strictly speaking, maybe we shouldn't check the `bit` at all, since we can't make universal assumptions here about engines' default responses.

**Comment by CalebFenton** [comment]
I appreciate the thoughtful reply. Perhaps a comment with a suggestion on
bit checking strategies in the test is enough.

**Comment by myhndl** [comment]
Fixed via: https://github.com/polyswarm/participant-template/commit/ac77b38f2812fb9b770805169358c5c0f1f332c7
